apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-rhtap-example
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pdave-tenant/nodejs-rhtap-example/nodejs-rhtap-example@sha256:a56f9e84f31ca644afcf56f99ba9a0de08236d413cdf4dc3d281495bc97c8ba2
        name: my-nodejs
        resources: {}
status: {}
