apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rhtap-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rhtap-example
    app.kubernetes.io/part-of: nodejs-rhtap-example
  name: nodejs-rhtap-example
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-rhtap-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-rhtap-example
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/pdave-tenant/nodejs-rhtap-example/nodejs-rhtap-example@sha256:a56f9e84f31ca644afcf56f99ba9a0de08236d413cdf4dc3d281495bc97c8ba2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
